name: Build Windows EXE

on:
  push:
    branches:
      - '**' # Trigger for any branch
  pull_request:
    branches:
      - '**' # Trigger for any branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable
        echo "${{ github.workspace }}\\flutter\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Install dependencies
      run: flutter pub get

    - name: Enable Windows desktop support
      run: flutter config --enable-windows-desktop

    - name: Build Windows EXE
      run: flutter build windows

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: app-windows-exe
        path: build\windows\runner\Release\*.exe
